---
layout: post
title: Validator
summary: Api documentation.
---

h3. Methods

"CheckDateTimeCondition":{{site.url}}/2012/12/02-CheckDateTimeCondition.html CheckThat(Func<DateTime> dateTimeToCheck)

"CheckDecimalCondition":{{site.url}}/2012/12/03-CheckDecimalCondition.html CheckThat(Func<decimal> decimalToCheck)
    
"CheckDoubleCondition":{{site.url}}/2012/12/04-CheckDoubleCondition.html CheckThat(Func<double> doubleToCheck)
    
"CheckEnumerableOfTCondition<T>":{{site.url}}/2012/12/05-CheckEnumerableOfTCondition-of-T.html CheckThat<T>(Func<IEnumerable<T>> enumerableToCheck)
    
"CheckIntegerCondition":{{site.url}}/2012/12/06-CheckIntegerCondition.html CheckThat(Func<int> integerToCheck)

"CheckObjectCondition":{{site.url}}/2012/12/07-CheckObjectCondition.html CheckThat(Func<object> objectToCheck)

"CheckNameValueCollectionCondition":{{site.url}}/2012/12/08-CheckNameValueCollectionCondition.html CheckThat(Func<NameValueCollection> 

"CheckStringCondition":{{site.url}}/2012/12/09-CheckStringCondition.html CheckThat(Func<string> stringToCheck)

"CheckXmlNodeCondition":{{site.url}}/2012/12/10-CheckXmlNodeCondition.html CheckThat(Func<XmlNode> nodeToCheck)

h3. Methods inherit from ExceptionThrower

void ThrowFirst()
__Throws the first Exception found during validation__

void Throw()
__Throw the "ErrorsCollectionException":{{site.url}}/2012-12-11-ErrorsCollectionException.html if at least one error is found during validation__

void Throw<E>:(object[] exceptionArguments) where E : Exception
__Throw Exception of type E if at least one error is found during validation__

"ErrorsCollectionException":{{site.url}}/2012-12-11-ErrorsCollectionException.html List()
